#程序自身自定义配置
app:  
  server: 
    accessUrl: http://10.0.0.21:800
    protocol: http://qq.2017zsx.com/protocol/agreement.html
    environment: dev
    postShare: http://qq.2017zsx.com/share/post.html
    newShare: http://qq.2017zsx.com/share/news.html
    workMatterShare: http://qq.2017zsx.com/share/news.html
    poliyShare: http://qq.2017zsx.com/share/news.html
    govermentShare: http://qq.2017zsx.com/share/news.html
  ffmpeg: 
    ffmpegPath: D:/ffmpeg-20180124-4dbae00-win64-static/bin/ffmpeg.exe   
#服务器配置
server: 
   servlet: 
      contextPath: /fwmp 
   port: 8086
   undertow: 
      worker-threads: 20
      buffer-size: 512
      io-threads: 2 
      sessionTimeout: 50
    #应用容器
   tomcat: 
      max-threads: 800
      uri-encoding: UTF-8
      #生成目录
      basedir: D:/springboot-tomcat-tmp
#日志配置
logging:
  path: D:/springboot-tomcat-tmp/log/
  level:  
    com.zsx: debug
    org.jooq: debug
    org.mybatis.spring: debug
    org.apache.ibatis.session.defaults.DefaultSqlSession: debug
    com.jarvis.cache: debug

#spring 配置
spring: 
   #redis配置
    redis: 
      host: 10.0.0.21
      port: 6379
      timeout: 10000
      pool: 
        max-active: 8  
        max- : -1  
        max-idle: 8  
        min-idle: 0  
      password: 5xdKrUINlenZLtk8
  #数据源配置
    datasource: 
        #initialization-mode: EMBEDDED
        #platform: dev
        url: jdbc:mysql://10.0.0.21:3306/zsx_fwmp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=true
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat,wall,log4j
        maxActive: 20
        initialSize: 5
        maxWait: 60000
        minIdle: 5
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20 
        useGlobalDataSourceStat: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #jackson    
    jackson:  
        date-format: yyyy-MM-dd HH:mm:ss

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mappers/app/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zsx.model
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
  configuration: 
    map-underscore-to-camel-case: true
    cache-enabled: true
    #lazy-Loading-Enabled: true
    #aggressive-Lazy-Loading: true
